# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ master ]
    tags:
      - 'v*.*.*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: get version number
        run: echo "R_V=${GITHUB_REF:11}" >> $GITHUB_ENV
      - name: test version number
        run: echo ${{ env.R_V }} 

      - name: Check out
        uses: actions/checkout@v2

      - name: Login to docker hub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image to docker hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: hp-web:${{ env.R_V }}
      
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PharsePWD }}
          port: 22
          script: docker run -dp 3000:3000 hp-web:${{ env.R_V }}
